/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x0E, 0x83, 0xA2, 0xAC, 0x15, 0x3B, 0x6D, 0x6C}

#define DYNAMIC_KEYMAP_LAYER_COUNT 12   


#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 2 }


#ifdef RGB_MATRIX_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define RGBLIGHT_LAYERS 
#define RGBLIGHT_MAX_LAYERS 12 
#define WS2812_PIO_USE_PIO1
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
#endif